### ISSUE TITLE
GitHub action for tutors-html static website deployment

### ISSUE THREAD

**Issue by tc-565** [tutors-sdk/tutors#272]
Hi. I am attempting to make a GitHub action in order to automatically build and deploy a tutors website with tutors-html each time a change is pushed. For testing, I forked [tutors-template](https://github.com/tutors-sdk/tutors-template).

I am able to build the website with Node v19.6.1 from my computer with tutors-html@2.6.2, but I am facing trouble when doing so with one of GitHub's runners, for which I have tried both Node v18.4.1 and v19.6.1. An error is thrown after a `Template render error` message, and the site doesn't get to build. I am not able to figure out why this different behaviour presents itself.

The deploy action can be consulted at [my fork](https://github.com/tutors-sdk/tutors-template/compare/master...tc-565:tutors-template:master), as well as the [logs](https://github.com/tc-565/tutors-template/actions/runs/4214733747/jobs/7315392009) of the run.

Kudos for this amazing project!
```
/opt/hostedtoolcache/node/19.6.1/×64/lib/node_modules/tutors-html/node_modules/nunjucks/src/environment.js:575
        throw err;
  Template render error: (/opt/hostedtoolcache/node/19.6.1/×64/lib/node_modules/tutors-html/src/views/Topic.njk)
  Template render error: (/opt/hostedtoolcache/node/19.6.1/x64/lib/node_modules/tutors-html/src/views/Topic.njk)
  Template render error: (/opt/hostedtoolcache/node/19.6.1/x64/lib/node_modules/tutors-html/src/views/Topic.njk)
  Error: template not found: components/cards/card.njk
    at Object._prettifyError (/opt/hostedtoolcache/node/19.6.1/x64/lib/node_modules/tutors-html/node_modules/nunjucks/src/lib.js:36:11)
    at /opt/hostedtoolcache/node/19.6.1/x64/lib/node_modules/tutors-html/node_modules/nunjucks/src/environment.js:563:19 at Template.root [as rootRenderFunc] (eval at _compile (/opt/hostedtoolcache/node/19.6.1/×64/1ib/node_modules/tutors-
html/node_modules/nunjucks/src/environment.js:633:18),<anonymous>:71:3)
    at Template. render (/opt/hostedtoolcache/node/19.6.1/×64/1ib/node_modules/tutors-html/node_modulles/nunjucks/src/environment.js:552:10)
    at /opt/hostedtoolcache/node/19.6.1/x64/lib/node _modules/tutors-htm1/node_modules/nunjucks/src/environment.js:366:27 at createTemplate(/opt/hostedtoolcache/node/19.6.1/×64/1ib/node_modules/tutors-html/node_modules/nunjucks/src/environment.js:315:9)
    at handle (/opt/hostedtoolcache/node/19.6.1/x64/1ib/node_modules/tutors-html/node_modules/nunjucks/src/environment.js:327:11)
    at /opt/hostedtoolcache/node/19.6.1/x64/lib/node_modules/tutors-html/node_modules/nunjucks/src/environment.js:339:9 at next (/opt/hostedtoolcache/node/19.6.1/×64/lib/node_modules/tutors-html/node_modules/nunjucks/src/lib.js:328:7)
    at Object.asyncIter/opt/hostedtoolcache/node/19.6.1/x64/lib/node_modules/tutors-html/node_modules/nunjucks/src/lib.js:334:3)
Node.js v19.6.1
```

**Comment by jordharr** [comment]
I have a feeling that our issue here is with the tutors-html package - your error

`Error: template not found: components/cards/card.njk`

this component is actually called Card.njk (note the capitals)

We will take a look further into this :)

**Comment by jordharr** [comment]
Version 2.6.3 of tutors-html has now fixed this, see logs from my deploy here :)

https://github.com/jordharr/tutors-template/actions/runs/4240879960/jobs/7370412100

Thanks for bringing this to our attention @tc-565 and if you have any other questions please feel free to get in touch!

**Comment by tc-565** [comment]
Thank you so much for the support!
